<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bjou</string>
	</array>
	<key>name</key>
	<string>bJou</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>flow control</string>
			<key>match</key>
			<string>\b(return|if|else|while|do|for|foreach|in|match|with|and|or|\&amp;\&amp;|\|\||break|continue)\b</string>
			<key>name</key>
			<string>keyword.control.bjou</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.bjou</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>types</string>
			<key>match</key>
			<string>\b(([ui](1|8|16|32|64))|f(32|64)|void|bool|char|short|int|long|float|double|unsigned|byte|string|file|list|dict)\b</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>general keywords</string>
			<key>match</key>
			<string>\b(const|macro|proc|extern|type|from|extends|interface|implements|abstract|alias|this|ref|enum|namespace|maybe|print|fail|new|raw|immut|delete|as|import|module|operator|sizeof|using)\b</string>
			<key>name</key>
			<string>keyword.other.bjou</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>procs and methods</string>
			<key>match</key>
			<string>\b([_a-zA-Z][_a-zA-Z0-9]*'*)(&lt;.*&gt;)?\(</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>val words</string>
			<key>match</key>
			<string>\b(not|true|false|nothing|some)\b</string>
			<key>name</key>
			<string>constant.numeric.bjou</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.identifier</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>identifiers</string>
			<key>match</key>
			<string>\b([_a-zA-Z][_a-zA-Z0-9]*'*)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.macro</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>macros</string>
			<key>match</key>
			<string>(\$[_a-zA-Z][_a-zA-Z0-9]*)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>decimal</string>
			<key>match</key>
			<string>((?&lt;=[^_a-zA-Z])-?[0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.bjou</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>float</string>
			<key>match</key>
			<string>((?&lt;=[^_a-zA-Z])-?[0-9].[0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.bjou</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>char</string>
			<key>match</key>
			<string>('([ \S]|\\.)')</string>
			<key>name</key>
			<string>constant.numeric.bjou</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>(\"(\\.|[^\"])*\")</string>
			<key>name</key>
			<string>string.double.bjou</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>single-line comments</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.bjou</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>multi-line comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.bjou</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.bjou</string>
	<key>uuid</key>
	<string>f7ecc55f-3a16-4c3c-8d82-c60cffd47693</string>
</dict>
</plist>
