/*
 * This file generates the __sys.bjou module to STDOUT.
 *
 * Brandon Kammerdiener
 * Feb 1, 2019
 */

#define _XOPEN_SOURCE

#include <stdio.h>
#include <sys/syscall.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <signal.h>
#include <sys/resource.h>
#include <stddef.h>

#define PRINT_SYS_NR_DECL(NR) printf("const "#NR" := SYS_NR_MOD + %d\n", (NR))
#define PRINT_SYS_CONSTANT_DECL(C) printf("const "#C" := %d\n", (C))

void pre() {
    printf(
"# __sys.bjou\n"
"# This file was generated by gen_sys.\n"
"# system calls\n"
"\n"
"module __sys\n"
"\n"
"import \"os.bjou\"\n"
"\n"
"extern nolibc_syscall(i64, i32, ...) : i32\n"
"\n"
"\\static_if{ os::OS != os::MACOS\n"
"    const SYS_NR_MOD := 0x0 }\n"
"\\static_if{ os::OS == os::MACOS\n"
"    const SYS_NR_MOD := 0x2000000 }\n"
"\n"
"type fd_t        = int\n"
"type mode_t      = u16\n"
"type time_t      = i64\n"
"type suseconds_t = i32\n"
"\n"
"type timeval {\n"
"    tv_sec  : time_t\n"
"    tv_usec : suseconds_t\n"
"}\n"
"type timezone {\n"
"    tz_minuteswest : i32\n"
"    tz_dsttime     : i32\n"
"}\n");
    printf(
"type timespec {\n"
"    tv_sec  : time_t\n"
"    tv_nsec : i%lu\n"
"}\n", 8 * sizeof(long));
    printf(
"proc time(t_p : time_t*) : time_t {\n"
"    tv := { timeval: }\n"
"    s  := gettimeofday(&tv, NULL as timezone*)\n"
"    if not t_p.isnull()    { @t_p = tv.tv_sec }\n"
"    return tv.tv_sec\n"
"}\n"
"proc sleep(s : u32) {\n"
"    elapsed := 0u32\n"
"    tv_beg := { timeval: }\n"
"    tv_now := { timeval: }\n"
"    gettimeofday(&tv_beg, NULL as timezone*)\n"
"    while elapsed < s {\n"
"        gettimeofday(&tv_now, NULL as timezone*)\n"
"        elapsed = tv_now.tv_sec - tv_beg.tv_sec\n"
"    }\n"
"}\n"
"proc usleep(u : u64) {\n"
"    elapsed := 0u64\n"
"    tv_beg := { timeval: }\n"
"    tv_now := { timeval: }\n"
"    gettimeofday(&tv_beg, NULL as timezone*)\n"
"    while elapsed < u {\n"
"        gettimeofday(&tv_now, NULL as timezone*)\n"
"        elapsed = ((tv_now.tv_sec * 1000000) + tv_now.tv_usec) - ((tv_beg.tv_sec * 1000000) + tv_beg.tv_usec)\n"
"    }\n"
"}\n");
printf("\n"
"type rusage {\n"
"    bytes : u8[%lu]\n"
"    proc ru_maxrss(this) : i64 {\n"
"        return @(((&(this.bytes[%lu])) as void*) as i64*)\n"
"    }\n"
"}\n", sizeof(struct rusage), offsetof(struct rusage, ru_maxrss));
printf("\n"
);

printf("\n");
}

void post() {
    printf(
"\n"
"proc write(fd : i32, buf : void*, nbyte : u64) : i64\n"
"    return nolibc_syscall(SYS_write, 3, fd, buf, nbyte)\n"
"\n"
"proc read(fd : i32, buf : void*, nbyte : u64) : i64\n"
"    return nolibc_syscall(SYS_read, 3, fd, buf, nbyte)\n"
"\n"
"proc open(path: char*, oflag : int) : i64\n"
"    return nolibc_syscall(SYS_open, 2, path, oflag)\n"
"\n"
"proc open(path: char*, oflag : int, mode : mode_t) : i64\n"
"    return nolibc_syscall(SYS_open, 3, path, oflag, mode)\n"
"\n"
"proc close(fd : int) : i64\n"
"    return nolibc_syscall(SYS_close, 1, fd)\n"
"\n"
"proc exit(status : int) : i64\n"
"    return nolibc_syscall(SYS_exit, 1, status)\n"
"\n"
"proc exit_group(status : int) : i64\n"
"    return nolibc_syscall(SYS_exit_group, 1, status)\n"
"\n"
"proc lseek(fd : int, offset : u64, whence : int) : u64\n"
"    return nolibc_syscall(SYS_lseek, 3, fd, offset, whence)\n"
"\n"
"proc access(path : char*, mode : int) : i64\n"
"    return nolibc_syscall(SYS_access, 2, path, mode)\n"
"\n"
"proc getpid() : i64\n"
"    return nolibc_syscall(SYS_getpid, 0)\n"
"\n"
"proc gettimeofday(tv : timeval*, tz : timezone*) : i64\n"
"    return nolibc_syscall(SYS_gettimeofday, 2, tv, tz)\n"
"\n"
"proc getrusage(who : int, usage : rusage*) : i64\n"
"    return nolibc_syscall(SYS_getrusage, 2, who, usage)\n"
"\n"
);

    printf("\n");

#ifdef __APPLE__
    printf(
"extern sysctlbyname(char*, void*, u%lu, void*, u%lu) : int\n",
    8 * sizeof(size_t), 8 * sizeof(size_t));
#endif
    printf(
"extern sysconf(int) : i%lu\n",
    8 * sizeof(long));

    printf("\n");

}

int main() {
    pre();

    PRINT_SYS_NR_DECL(SYS_write);
    PRINT_SYS_NR_DECL(SYS_read);
    PRINT_SYS_NR_DECL(SYS_open);
    PRINT_SYS_NR_DECL(SYS_close);
    PRINT_SYS_NR_DECL(SYS_exit);
    PRINT_SYS_NR_DECL(SYS_exit_group);
    PRINT_SYS_NR_DECL(SYS_lseek);
    PRINT_SYS_NR_DECL(SYS_access);
    PRINT_SYS_NR_DECL(SYS_getpid);
    PRINT_SYS_NR_DECL(SYS_gettimeofday);
    PRINT_SYS_NR_DECL(SYS_getrusage);

    PRINT_SYS_CONSTANT_DECL(S_IRWXU);
    PRINT_SYS_CONSTANT_DECL(S_IRUSR);
    PRINT_SYS_CONSTANT_DECL(S_IWUSR);
    PRINT_SYS_CONSTANT_DECL(S_IXUSR);
    PRINT_SYS_CONSTANT_DECL(S_IRWXG);
    PRINT_SYS_CONSTANT_DECL(S_IRGRP);
    PRINT_SYS_CONSTANT_DECL(S_IWGRP);
    PRINT_SYS_CONSTANT_DECL(S_IXGRP);
    PRINT_SYS_CONSTANT_DECL(S_IRWXO);
    PRINT_SYS_CONSTANT_DECL(S_IROTH);
    PRINT_SYS_CONSTANT_DECL(S_IWOTH);
    PRINT_SYS_CONSTANT_DECL(S_IXOTH);
    PRINT_SYS_CONSTANT_DECL(O_RDONLY);
    PRINT_SYS_CONSTANT_DECL(O_WRONLY);
    PRINT_SYS_CONSTANT_DECL(O_RDWR);
    PRINT_SYS_CONSTANT_DECL(O_APPEND);
    PRINT_SYS_CONSTANT_DECL(O_CREAT);
    PRINT_SYS_CONSTANT_DECL(O_TRUNC);
    PRINT_SYS_CONSTANT_DECL(O_EXCL);
    PRINT_SYS_CONSTANT_DECL(SEEK_SET);
    PRINT_SYS_CONSTANT_DECL(SEEK_CUR);
    PRINT_SYS_CONSTANT_DECL(SEEK_END);
    PRINT_SYS_CONSTANT_DECL(F_OK);

    PRINT_SYS_CONSTANT_DECL(SIGHUP);
    PRINT_SYS_CONSTANT_DECL(SIGINT);
    PRINT_SYS_CONSTANT_DECL(SIGQUIT);
    PRINT_SYS_CONSTANT_DECL(SIGILL);
    PRINT_SYS_CONSTANT_DECL(SIGTRAP);
    PRINT_SYS_CONSTANT_DECL(SIGABRT);
#ifdef SIGPOLL
    PRINT_SYS_CONSTANT_DECL(SIGPOLL);
#endif
    PRINT_SYS_CONSTANT_DECL(SIGIOT);
    PRINT_SYS_CONSTANT_DECL(SIGFPE);
    PRINT_SYS_CONSTANT_DECL(SIGKILL);
    PRINT_SYS_CONSTANT_DECL(SIGBUS);
    PRINT_SYS_CONSTANT_DECL(SIGSEGV);
    PRINT_SYS_CONSTANT_DECL(SIGSYS);
    PRINT_SYS_CONSTANT_DECL(SIGPIPE);
    PRINT_SYS_CONSTANT_DECL(SIGALRM);
    PRINT_SYS_CONSTANT_DECL(SIGTERM);
    PRINT_SYS_CONSTANT_DECL(SIGURG);
    PRINT_SYS_CONSTANT_DECL(SIGSTOP);
    PRINT_SYS_CONSTANT_DECL(SIGTSTP);
    PRINT_SYS_CONSTANT_DECL(SIGCONT);
    PRINT_SYS_CONSTANT_DECL(SIGCHLD);
    PRINT_SYS_CONSTANT_DECL(SIGTTIN);
    PRINT_SYS_CONSTANT_DECL(SIGTTOU);
    PRINT_SYS_CONSTANT_DECL(SIGIO);
    PRINT_SYS_CONSTANT_DECL(SIGXCPU);
    PRINT_SYS_CONSTANT_DECL(SIGXFSZ);
    PRINT_SYS_CONSTANT_DECL(SIGVTALRM);
    PRINT_SYS_CONSTANT_DECL(SIGPROF);
    PRINT_SYS_CONSTANT_DECL(SIGWINCH);
    PRINT_SYS_CONSTANT_DECL(SIGUSR1);
    PRINT_SYS_CONSTANT_DECL(SIGUSR2);

    PRINT_SYS_CONSTANT_DECL(_SC_NPROCESSORS_ONLN);

    post();

    return 0;
}
