/*
 * This file generates the __pthread.bjou module to STDOUT.
 *
 * Brandon Kammerdiener
 * May 8, 2019
 */

#include <stdio.h>
#include <pthread.h>

#define PRINT_PTH_CONSTANT_INT_DECL(C) printf("const "#C" := %d\n", (C))
#define PRINT_PTH_CONSTANT_PTR_DECL(C) printf("const "#C" := %p as void*\n", (C))
#define PRINT_OPAQUE_STRUCT_DECL(name, size) printf("type "#name" {\n    bytes : char[%lu]\n}\n", (size))

void pre() {
    printf(
"# __pthread.bjou\n"
"# This file was generated by gen_sys.\n"
"# pthread\n"
"\n"
"module __pthread\n"
"\n");

    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_CANCEL_ASYNCHRONOUS);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_CANCEL_ENABLE);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_CANCEL_DEFERRED);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_CANCEL_DISABLE);
    PRINT_PTH_CONSTANT_PTR_DECL(PTHREAD_CANCELED);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_CREATE_DETACHED);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_CREATE_JOINABLE);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_EXPLICIT_SCHED);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_INHERIT_SCHED);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_MUTEX_DEFAULT);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_MUTEX_ERRORCHECK);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_MUTEX_NORMAL);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_MUTEX_RECURSIVE);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_PRIO_INHERIT);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_PRIO_NONE);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_PRIO_PROTECT);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_PROCESS_SHARED);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_PROCESS_PRIVATE);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_SCOPE_PROCESS);
    PRINT_PTH_CONSTANT_INT_DECL(PTHREAD_SCOPE_SYSTEM);
    
    printf("\n");

    PRINT_OPAQUE_STRUCT_DECL(pthread_attr_t, sizeof(pthread_attr_t));    
    PRINT_OPAQUE_STRUCT_DECL(pthread_cond_t, sizeof(pthread_cond_t));    
    PRINT_OPAQUE_STRUCT_DECL(pthread_condattr_t, sizeof(pthread_condattr_t));    
    PRINT_OPAQUE_STRUCT_DECL(pthread_mutex_t, sizeof(pthread_mutex_t));    
    PRINT_OPAQUE_STRUCT_DECL(pthread_mutexattr_t, sizeof(pthread_mutexattr_t));    
    PRINT_OPAQUE_STRUCT_DECL(pthread_once_t, sizeof(pthread_once_t));    
    PRINT_OPAQUE_STRUCT_DECL(pthread_rwlock_t, sizeof(pthread_rwlock_t));    
    PRINT_OPAQUE_STRUCT_DECL(pthread_rwlockattr_t, sizeof(pthread_rwlockattr_t));    
    PRINT_OPAQUE_STRUCT_DECL(_pthread_t, sizeof(*(pthread_t){NULL}));
    printf("type pthread_t = _pthread_t*\n");
    printf("type pthread_key_t = u%lu\n", 8 * sizeof(long));

    printf("\n");
}

void post() {

}

int main() {
    pre();

    printf("extern pthread_attr_destroy(pthread_attr_t *) : int \n");
    printf("extern pthread_attr_getdetachstate( pthread_attr_t *, int *) : int \n");
    printf("extern pthread_attr_getguardsize( pthread_attr_t *, u%lu *) : int \n", 8 * sizeof(size_t));
    printf("extern pthread_attr_getinheritsched( pthread_attr_t *, int *) : int \n");
    printf("extern pthread_attr_getschedparam( pthread_attr_t *,  void*) : int \n");
    printf("extern pthread_attr_getschedpolicy( pthread_attr_t *, int *) : int \n");
    printf("extern pthread_attr_getscope( pthread_attr_t *, int *) : int \n");
    printf("extern pthread_attr_getstackaddr( pthread_attr_t *, void **) : int \n");
    printf("extern pthread_attr_getstacksize( pthread_attr_t *, u%lu *) : int \n", 8 * sizeof(size_t));
    printf("extern pthread_attr_init(pthread_attr_t *) : int \n");
    printf("extern pthread_attr_setdetachstate(pthread_attr_t *, int) : int \n");
    printf("extern pthread_attr_setguardsize(pthread_attr_t *, u%lu) : int \n", 8 * sizeof(size_t));
    printf("extern pthread_attr_setinheritsched(pthread_attr_t *, int) : int \n");
    printf("extern pthread_attr_setschedparam(pthread_attr_t *,   void*) : int \n");
    printf("extern pthread_attr_setschedpolicy(pthread_attr_t *, int) : int \n");
    printf("extern pthread_attr_setscope(pthread_attr_t *, int) : int \n");
    printf("extern pthread_attr_setstackaddr(pthread_attr_t *, void *) : int \n");
    printf("extern pthread_attr_setstacksize(pthread_attr_t *, u%lu) : int \n", 8 * sizeof(size_t));
    printf("extern pthread_cancel(pthread_t) : int \n");
    printf("extern pthread_cleanup_push(<(void*)>, void *)\n");
    printf("extern pthread_cleanup_pop(int)\n");
    printf("extern pthread_cond_broadcast(pthread_cond_t *) : int \n");
    printf("extern pthread_cond_destroy(pthread_cond_t *) : int \n");
    printf("extern pthread_cond_init(pthread_cond_t *,  pthread_condattr_t *) : int \n");
    printf("extern pthread_cond_signal(pthread_cond_t *) : int \n");
    printf("extern pthread_cond_timedwait(pthread_cond_t *,  pthread_mutex_t *,   void*) : int \n");
    printf("extern pthread_cond_wait(pthread_cond_t *, pthread_mutex_t *) : int \n");
    printf("extern pthread_condattr_destroy(pthread_condattr_t *) : int \n");
    printf("extern pthread_condattr_getpshared( pthread_condattr_t *, int *) : int \n");
    printf("extern pthread_condattr_init(pthread_condattr_t *) : int \n");
    printf("extern pthread_condattr_setpshared(pthread_condattr_t *, int) : int \n");
    printf("extern pthread_create(pthread_t *,  pthread_attr_t *, <(void*) : void*>, void *) : int \n");
    printf("extern pthread_detach(pthread_t) : int \n");
    printf("extern pthread_equal(pthread_t, pthread_t) : int \n");
    printf("extern pthread_exit(void *)\n");
    printf("extern pthread_getconcurrency() : int \n");
    printf("extern pthread_getschedparam(pthread_t, int *,  void*) : int \n");
    printf("extern pthread_getspecific(pthread_key_t) : void* \n");
    printf("extern pthread_join(pthread_t, void **) : int \n");
    printf("extern pthread_key_create(pthread_key_t *, <(void*)>) : int \n");
    printf("extern pthread_key_delete(pthread_key_t) : int \n");
    printf("extern pthread_mutex_destroy(pthread_mutex_t *) : int \n");
    printf("extern pthread_mutex_getprioceiling( pthread_mutex_t *, int *) : int \n");
    printf("extern pthread_mutex_init(pthread_mutex_t *,  pthread_mutexattr_t *) : int \n");
    printf("extern pthread_mutex_lock(pthread_mutex_t *) : int \n");
    printf("extern pthread_mutex_setprioceiling(pthread_mutex_t *, int, int *) : int \n");
    printf("extern pthread_mutex_trylock(pthread_mutex_t *) : int \n");
    printf("extern pthread_mutex_unlock(pthread_mutex_t *) : int \n");
    printf("extern pthread_mutexattr_destroy(pthread_mutexattr_t *) : int \n");
    printf("extern pthread_mutexattr_getprioceiling( pthread_mutexattr_t *, int *) : int \n");
    printf("extern pthread_mutexattr_getprotocol( pthread_mutexattr_t *, int *) : int \n");
    printf("extern pthread_mutexattr_getpshared( pthread_mutexattr_t *, int *) : int \n");
    printf("extern pthread_mutexattr_gettype( pthread_mutexattr_t *, int *) : int \n");
    printf("extern pthread_mutexattr_init(pthread_mutexattr_t *) : int \n");
    printf("extern pthread_mutexattr_setprioceiling(pthread_mutexattr_t *, int) : int \n");
    printf("extern pthread_mutexattr_setprotocol(pthread_mutexattr_t *, int) : int \n");
    printf("extern pthread_mutexattr_setpshared(pthread_mutexattr_t *, int) : int \n");
    printf("extern pthread_mutexattr_settype(pthread_mutexattr_t *, int) : int \n");
    printf("extern pthread_once(pthread_once_t *, <()>) : int \n");
    printf("extern pthread_rwlock_destroy(pthread_rwlock_t *) : int \n");
    printf("extern pthread_rwlock_init(pthread_rwlock_t *,  pthread_rwlockattr_t *) : int \n");
    printf("extern pthread_rwlock_rdlock(pthread_rwlock_t *) : int \n");
    printf("extern pthread_rwlock_tryrdlock(pthread_rwlock_t *) : int \n");
    printf("extern pthread_rwlock_trywrlock(pthread_rwlock_t *) : int \n");
    printf("extern pthread_rwlock_unlock(pthread_rwlock_t *) : int \n");
    printf("extern pthread_rwlock_wrlock(pthread_rwlock_t *) : int \n");
    printf("extern pthread_rwlockattr_destroy(pthread_rwlockattr_t *) : int \n");
    printf("extern pthread_rwlockattr_getpshared( pthread_rwlockattr_t *, int *) : int \n");
    printf("extern pthread_rwlockattr_init(pthread_rwlockattr_t *) : int \n");
    printf("extern pthread_rwlockattr_setpshared(pthread_rwlockattr_t *, int) : int \n");
    printf("extern pthread_self() : pthread_t \n");
    printf("extern pthread_setcancelstate(int, int *) : int \n");
    printf("extern pthread_setcanceltype(int, int *) : int \n");
    printf("extern pthread_setconcurrency(int) : int \n");
    printf("extern pthread_setschedparam(pthread_t, int ,   void*) : int \n");
    printf("extern pthread_setspecific(pthread_key_t,  void *) : int \n");
    printf("extern pthread_testcancel()\n");

    post();

    return 0;
}

